// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_screen1
void ui_screen1_screen_init(void);
lv_obj_t * ui_screen1;
lv_obj_t * ui_button1;
lv_obj_t * ui_button2;
lv_obj_t * ui_button3;
lv_obj_t * ui_image1;
lv_obj_t * ui_image2;
lv_obj_t * ui_image3;
lv_obj_t * ui_label2;
lv_obj_t * ui_label1;
lv_obj_t * ui_image10;
lv_obj_t * ui_image11;
lv_obj_t * ui_label15;
lv_obj_t * ui_label16;
// CUSTOM VARIABLES


// SCREEN: ui_screen2
void ui_screen2_screen_init(void);
lv_obj_t * ui_screen2;
lv_obj_t * ui_button4;
lv_obj_t * ui_button5;
lv_obj_t * ui_button6;
lv_obj_t * ui_image4;
lv_obj_t * ui_image5;
lv_obj_t * ui_image6;
lv_obj_t * ui_label4;
lv_obj_t * ui_label5;
lv_obj_t * ui_label6;
lv_obj_t * ui_label7;
lv_obj_t * ui_label3;
lv_obj_t * ui_label8;
lv_obj_t * ui_label17;
lv_obj_t * ui_label18;
lv_obj_t * ui_label19;
// CUSTOM VARIABLES


// SCREEN: ui_screen3
void ui_screen3_screen_init(void);
lv_obj_t * ui_screen3;
lv_obj_t * ui_button7;
lv_obj_t * ui_button8;
lv_obj_t * ui_button9;
lv_obj_t * ui_image7;
lv_obj_t * ui_image8;
lv_obj_t * ui_image9;
lv_obj_t * ui_label9;
lv_obj_t * ui_label10;
lv_obj_t * ui_label11;
lv_obj_t * ui_label12;
lv_obj_t * ui_label13;
lv_obj_t * ui_label14;
lv_obj_t * ui_label20;
lv_obj_t * ui_label21;
lv_obj_t * ui_label22;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_screen1_screen_init();
    ui_screen2_screen_init();
    ui_screen3_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_screen1);
}
