// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_screen1
void ui_screen1_screen_init(void);
extern lv_obj_t * ui_screen1;
extern lv_obj_t * ui_button1;
extern lv_obj_t * ui_button2;
extern lv_obj_t * ui_button3;
extern lv_obj_t * ui_image1;
extern lv_obj_t * ui_image2;
extern lv_obj_t * ui_image3;
extern lv_obj_t * ui_label2;
extern lv_obj_t * ui_label1;
extern lv_obj_t * ui_image10;
extern lv_obj_t * ui_image11;
extern lv_obj_t * ui_label15;
extern lv_obj_t * ui_label16;
extern lv_obj_t *ui_label_condition;
// CUSTOM VARIABLES

// SCREEN: ui_screen2
void ui_screen2_screen_init(void);
extern lv_obj_t * ui_screen2;
extern lv_obj_t * ui_button4;
extern lv_obj_t * ui_button5;
extern lv_obj_t * ui_button6;
extern lv_obj_t * ui_image4;
extern lv_obj_t * ui_image5;
extern lv_obj_t * ui_image6;
extern lv_obj_t * ui_label4;
extern lv_obj_t * ui_label5;
extern lv_obj_t * ui_label6;
extern lv_obj_t * ui_label7;
extern lv_obj_t * ui_label3;
extern lv_obj_t * ui_label8;
extern lv_obj_t * ui_label17;
extern lv_obj_t * ui_label18;
extern lv_obj_t * ui_label19;
// CUSTOM VARIABLES

// SCREEN: ui_screen3
void ui_screen3_screen_init(void);
extern lv_obj_t * ui_screen3;
extern lv_obj_t * ui_button7;
extern lv_obj_t * ui_button8;
extern lv_obj_t * ui_button9;
extern lv_obj_t * ui_image7;
extern lv_obj_t * ui_image8;
extern lv_obj_t * ui_image9;
extern lv_obj_t * ui_label9;
extern lv_obj_t * ui_label10;
extern lv_obj_t * ui_label11;
extern lv_obj_t * ui_label12;
extern lv_obj_t * ui_label13;
extern lv_obj_t * ui_label14;
extern lv_obj_t * ui_label20;
extern lv_obj_t * ui_label21;
extern lv_obj_t * ui_label22;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_humitemp_png);    // assets/humitemp.png
LV_IMG_DECLARE(ui_img_fire_png);    // assets/fire.png
LV_IMG_DECLARE(ui_img_plug_png);    // assets/plug.png
LV_IMG_DECLARE(ui_img_celsius_png);    // assets/celsius.png
LV_IMG_DECLARE(ui_img_percent_png);    // assets/percent.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
