// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_COMP_BUTTON2_H
#define _UI_COMP_BUTTON2_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Button2
#define UI_COMP_BUTTON2_BUTTON2 0
#define _UI_COMP_BUTTON2_NUM 1
lv_obj_t * ui_button2_create(lv_obj_t * comp_parent);
void ui_event_comp_button2_button2(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
