// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"


void ui_event_comp_button2_button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_button2 = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screen2, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_screen2_screen_init);
    }
}

// COMPONENT Button2

lv_obj_t * ui_button2_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_button2;
    cui_button2 = lv_button_create(comp_parent);
    lv_obj_set_width(cui_button2, 87);
    lv_obj_set_height(cui_button2, 76);
    lv_obj_set_x(cui_button2, 2);
    lv_obj_set_y(cui_button2, -73);
    lv_obj_set_align(cui_button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_button2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON2_NUM);
    children[UI_COMP_BUTTON2_BUTTON2] = cui_button2;
    lv_obj_add_event_cb(cui_button2, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_button2, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_button2, ui_event_comp_button2_button2, LV_EVENT_ALL, children);
    ui_comp_button2_create_hook(cui_button2);
    return cui_button2;
}

