// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"


void ui_event_comp_button1_button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_button1 = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screen1, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_screen1_screen_init);
    }
}

// COMPONENT Button1

lv_obj_t * ui_button1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_button1;
    cui_button1 = lv_button_create(comp_parent);
    lv_obj_set_width(cui_button1, 87);
    lv_obj_set_height(cui_button1, 76);
    lv_obj_set_x(cui_button1, -100);
    lv_obj_set_y(cui_button1, -73);
    lv_obj_set_align(cui_button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_button1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON1_NUM);
    children[UI_COMP_BUTTON1_BUTTON1] = cui_button1;
    lv_obj_add_event_cb(cui_button1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_button1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_button1, ui_event_comp_button1_button1, LV_EVENT_ALL, children);
    ui_comp_button1_create_hook(cui_button1);
    return cui_button1;
}

