// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_COMP_BUTTON1_H
#define _UI_COMP_BUTTON1_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Button1
#define UI_COMP_BUTTON1_BUTTON1 0
#define _UI_COMP_BUTTON1_NUM 1
lv_obj_t * ui_button1_create(lv_obj_t * comp_parent);
void ui_event_comp_button1_button1(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
