// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: TFT_Project

#include "ui.h"

void ui_comp_Button1_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Button2_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Button3_create_hook(lv_obj_t * comp)
{
}

void ui_comp_button1_create_hook(lv_obj_t * comp)
{
}

void ui_comp_button2_create_hook(lv_obj_t * comp)
{
}

void ui_comp_button3_create_hook(lv_obj_t * comp)
{
}
