// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_screen3_screen_init(void)
{
    ui_screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screen3, lv_color_hex(0x4A5FC2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screen3, lv_color_hex(0x7AA0BE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_screen3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button7 = ui_button1_create(ui_screen3);
    lv_obj_set_x(ui_button7, -100);
    lv_obj_set_y(ui_button7, -73);

    ui_button8 = ui_button2_create(ui_screen3);
    lv_obj_set_x(ui_button8, 2);
    lv_obj_set_y(ui_button8, -73);

    ui_button9 = ui_button3_create(ui_screen3);
    lv_obj_set_x(ui_button9, 103);
    lv_obj_set_y(ui_button9, -74);

    ui_image7 = lv_image_create(ui_screen3);
    lv_image_set_src(ui_image7, &ui_img_humitemp_png);
    lv_obj_set_width(ui_image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image7, -99);
    lv_obj_set_y(ui_image7, -72);
    lv_obj_set_align(ui_image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_image8 = lv_image_create(ui_screen3);
    lv_image_set_src(ui_image8, &ui_img_fire_png);
    lv_obj_set_width(ui_image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image8, 2);
    lv_obj_set_y(ui_image8, -72);
    lv_obj_set_align(ui_image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_image9 = lv_image_create(ui_screen3);
    lv_image_set_src(ui_image9, &ui_img_plug_png);
    lv_obj_set_width(ui_image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image9, 104);
    lv_obj_set_y(ui_image9, -74);
    lv_obj_set_align(ui_image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image9, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_label9 = lv_label_create(ui_screen3);
    lv_obj_set_width(ui_label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label9, -87);
    lv_obj_set_y(ui_label9, -5);
    lv_obj_set_align(ui_label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label9, "Current");
    lv_obj_set_style_text_color(ui_label9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_label9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label9, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label10 = lv_label_create(ui_screen3);
    lv_obj_set_width(ui_label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label10, -81);
    lv_obj_set_y(ui_label10, 36);
    lv_obj_set_align(ui_label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label10, "Power");
    lv_obj_set_style_text_color(ui_label10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_label10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label10, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label11 = lv_label_create(ui_screen3);
    lv_obj_set_width(ui_label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label11, -83);
    lv_obj_set_y(ui_label11, 82);
    lv_obj_set_align(ui_label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label11, "Energy");
    lv_obj_set_style_text_color(ui_label11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_label11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label11, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label12 = lv_label_create(ui_screen3);
    lv_obj_set_width(ui_label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label12, 76);
    lv_obj_set_y(ui_label12, -9);
    lv_obj_set_align(ui_label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label12, "(A)");
    lv_obj_set_style_text_color(ui_label12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label13 = lv_label_create(ui_screen3);
    lv_obj_set_width(ui_label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label13, 77);
    lv_obj_set_y(ui_label13, 35);
    lv_obj_set_align(ui_label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label13, "(W)");
    lv_obj_set_style_text_color(ui_label13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label14 = lv_label_create(ui_screen3);
    lv_obj_set_width(ui_label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label14, 76);
    lv_obj_set_y(ui_label14, 84);
    lv_obj_set_align(ui_label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label14, "(kWh)");
    lv_obj_set_style_text_color(ui_label14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label20 = lv_label_create(ui_screen3);
    lv_obj_set_width(ui_label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label20, -10);
    lv_obj_set_y(ui_label20, -7);
    lv_obj_set_align(ui_label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label20, "20");
    lv_obj_set_style_text_color(ui_label20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label20, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label21 = lv_label_create(ui_screen3);
    lv_obj_set_width(ui_label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label21, -10);
    lv_obj_set_y(ui_label21, 37);
    lv_obj_set_align(ui_label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label21, "20");
    lv_obj_set_style_text_color(ui_label21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label21, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label22 = lv_label_create(ui_screen3);
    lv_obj_set_width(ui_label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label22, -10);
    lv_obj_set_y(ui_label22, 83);
    lv_obj_set_align(ui_label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label22, "20");
    lv_obj_set_style_text_color(ui_label22, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label22, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);


}
