// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_screen2_screen_init(void)
{
    ui_screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screen2, lv_color_hex(0x4A5FC2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screen2, lv_color_hex(0x7AA0BE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_screen2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button4 = ui_button1_create(ui_screen2);
    lv_obj_set_x(ui_button4, -100);
    lv_obj_set_y(ui_button4, -73);

    ui_button5 = ui_button2_create(ui_screen2);
    lv_obj_set_x(ui_button5, 2);
    lv_obj_set_y(ui_button5, -73);

    ui_button6 = ui_button3_create(ui_screen2);
    lv_obj_set_x(ui_button6, 103);
    lv_obj_set_y(ui_button6, -74);

    ui_image4 = lv_image_create(ui_screen2);
    lv_image_set_src(ui_image4, &ui_img_humitemp_png);
    lv_obj_set_width(ui_image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image4, -99);
    lv_obj_set_y(ui_image4, -72);
    lv_obj_set_align(ui_image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_image5 = lv_image_create(ui_screen2);
    lv_image_set_src(ui_image5, &ui_img_fire_png);
    lv_obj_set_width(ui_image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image5, 2);
    lv_obj_set_y(ui_image5, -72);
    lv_obj_set_align(ui_image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_image6 = lv_image_create(ui_screen2);
    lv_image_set_src(ui_image6, &ui_img_plug_png);
    lv_obj_set_width(ui_image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image6, 104);
    lv_obj_set_y(ui_image6, -74);
    lv_obj_set_align(ui_image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_label4 = lv_label_create(ui_screen2);
    lv_obj_set_width(ui_label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label4, -76);
    lv_obj_set_y(ui_label4, -2);
    lv_obj_set_align(ui_label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label4, "LPG");
    lv_obj_set_style_text_color(ui_label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label5 = lv_label_create(ui_screen2);
    lv_obj_set_width(ui_label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label5, -72);
    lv_obj_set_y(ui_label5, 50);
    lv_obj_set_align(ui_label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label5, "CO\n");
    lv_obj_set_style_text_color(ui_label5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label6 = lv_label_create(ui_screen2);
    lv_obj_set_width(ui_label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label6, -86);
    lv_obj_set_y(ui_label6, 82);
    lv_obj_set_align(ui_label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label6, "SMOKE");
    lv_obj_set_style_text_color(ui_label6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label7 = lv_label_create(ui_screen2);
    lv_obj_set_width(ui_label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label7, 83);
    lv_obj_set_y(ui_label7, -5);
    lv_obj_set_align(ui_label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label7, "(ppm)");
    lv_obj_set_style_text_color(ui_label7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label3 = lv_label_create(ui_screen2);
    lv_obj_set_width(ui_label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label3, 84);
    lv_obj_set_y(ui_label3, 38);
    lv_obj_set_align(ui_label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label3, "(ppm)");
    lv_obj_set_style_text_color(ui_label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label8 = lv_label_create(ui_screen2);
    lv_obj_set_width(ui_label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label8, 85);
    lv_obj_set_y(ui_label8, 81);
    lv_obj_set_align(ui_label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label8, "(ppm)");
    lv_obj_set_style_text_color(ui_label8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label17 = lv_label_create(ui_screen2);
    lv_obj_set_width(ui_label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label17, -6);
    lv_obj_set_y(ui_label17, -3);
    lv_obj_set_align(ui_label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label17, "60");
    lv_obj_set_style_text_color(ui_label17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label17, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label18 = lv_label_create(ui_screen2);
    lv_obj_set_width(ui_label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label18, -5);
    lv_obj_set_y(ui_label18, 39);
    lv_obj_set_align(ui_label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label18, "60");
    lv_obj_set_style_text_color(ui_label18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label18, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label19 = lv_label_create(ui_screen2);
    lv_obj_set_width(ui_label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label19, -4);
    lv_obj_set_y(ui_label19, 81);
    lv_obj_set_align(ui_label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label19, "60");
    lv_obj_set_style_text_color(ui_label19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label19, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);


}
