// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_screen1_screen_init(void)
{
    ui_screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screen1, lv_color_hex(0x4A5FC2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screen1, lv_color_hex(0x7AA0BE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_screen1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button1 = ui_button1_create(ui_screen1);
    lv_obj_set_x(ui_button1, -100);
    lv_obj_set_y(ui_button1, -73);

    ui_button2 = ui_button2_create(ui_screen1);
    lv_obj_set_x(ui_button2, 2);
    lv_obj_set_y(ui_button2, -73);

    ui_button3 = ui_button3_create(ui_screen1);
    lv_obj_set_x(ui_button3, 103);
    lv_obj_set_y(ui_button3, -74);

    ui_image1 = lv_image_create(ui_screen1);
    lv_image_set_src(ui_image1, &ui_img_humitemp_png);
    lv_obj_set_width(ui_image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image1, -99);
    lv_obj_set_y(ui_image1, -72);
    lv_obj_set_align(ui_image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_image2 = lv_image_create(ui_screen1);
    lv_image_set_src(ui_image2, &ui_img_fire_png);
    lv_obj_set_width(ui_image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image2, 2);
    lv_obj_set_y(ui_image2, -72);
    lv_obj_set_align(ui_image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_image3 = lv_image_create(ui_screen1);
    lv_image_set_src(ui_image3, &ui_img_plug_png);
    lv_obj_set_width(ui_image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image3, 104);
    lv_obj_set_y(ui_image3, -74);
    lv_obj_set_align(ui_image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_label2 = lv_label_create(ui_screen1);
    lv_obj_set_width(ui_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label2, -56);
    lv_obj_set_y(ui_label2, 59);
    lv_obj_set_align(ui_label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2, "Humidity");
    lv_obj_set_style_text_color(ui_label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label1 = lv_label_create(ui_screen1);
    lv_obj_set_width(ui_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label1, -67);
    lv_obj_set_y(ui_label1, 12);
    lv_obj_set_align(ui_label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1, "Temperature");
    lv_obj_set_style_text_color(ui_label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_image10 = lv_image_create(ui_screen1);
    lv_image_set_src(ui_image10, &ui_img_celsius_png);
    lv_obj_set_width(ui_image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image10, 86);
    lv_obj_set_y(ui_image10, 12);
    lv_obj_set_align(ui_image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image10, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_image10, 150);

    ui_image11 = lv_image_create(ui_screen1);
    lv_image_set_src(ui_image11, &ui_img_percent_png);
    lv_obj_set_width(ui_image11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image11, 88);
    lv_obj_set_y(ui_image11, 58);
    lv_obj_set_align(ui_image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image11, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_image11, 130);

    ui_label15 = lv_label_create(ui_screen1);
    lv_obj_set_width(ui_label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label15, 27);
    lv_obj_set_y(ui_label15, 10);
    lv_obj_set_align(ui_label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label15, "30.00");
    lv_obj_set_style_text_color(ui_label15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label15, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label16 = lv_label_create(ui_screen1);
    lv_obj_set_width(ui_label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label16, 30);
    lv_obj_set_y(ui_label16, 59);
    lv_obj_set_align(ui_label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label16, "30.00");
    lv_obj_set_style_text_color(ui_label16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label16, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
}
